server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
