server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/order-service
    username: kagami
    password: kagami

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8082
        auto.register.schemas: true

    listener:
      # This configures the default error handler for all @KafkaListener methods
      common-error-handler:
        enabled: true
        # Specifies that the DLT should be used after retries are exhausted
        dlt-enabled: true 
        # Defines the retry behavior
        back-off:
          # Start with a 1-second delay
          initial-interval: 1000 
          # Double the delay for each subsequent retry
          multiplier: 2.0
          # Set a maximum delay of 10 seconds
          max-interval: 10000
        # Total attempts = 1 initial + 3 retries
        max-attempts: 4 
        # Specify exceptions that should NOT be retried (e.g., bad data)
        not-retryable-exceptions:
          - org.springframework.messaging.converter.MessageConversionException
          - java.lang.IllegalArgumentException
      ack-mode: RECORD
      type: SINGLE
      dead-letter-publishing:
        enabled: true
        topic-suffix: .DLT
        delimiter: ""

    consumer:
      bootstrap-servers: kafka:29092
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://schema-registry:8082
        specific.avro.reader: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: kagami
    password: kagami
    exchanges:
      orders-exchange: "orders.exchange"
    routing-keys:
      order-created-key: "order.created"
      order-shipped-key: "order.shipped"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  
application:
  config:
    customer-url: http://api-gateway:8222/api/v1/customers
    payment-url: http://api-gateway:8222/api/v1/payments
    product-url: http://api-gateway:8222/api/v1/products

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
